spring:
  application:
    name: gulimall-cart
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.50.2
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.3:8848
    sentinel:
      transport:
        dashboard: 192.168.50.3:8333
        port: 8719
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://192.168.50.2:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 31000
  servlet:
    session:
      timeout: 30m
