spring:
  cloud:
    gateway:
      routes:
      - id: test_route
        uri: https://www.baidu.com
        predicates:
          - Query=url,baidu

      - id: qq_route
        uri: https://www.qq.com
        predicates:
          - Query=url,qq

      - id: sl_route
        uri: https://www.slienceme.cn
        predicates:
          - Query=url,slience_me