spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.50.2:3306/gulimall_ums?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.3:8848
    sentinel:
      transport:
        dashboard: 192.168.50.3:8333
        port: 8719
  application:
    name: gulimall-member
  thymeleaf:
    cache: false
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # classpath*表示不仅扫描自己的类路径，引用的jar包也扫描
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8000


logging:
  level:
    cn.slienceme.gulimall: debug
