spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.3:8848
    alicloud:
      access-key:
      secret-key:
      oss:
        bucket: slienceme
        endpoint:
        domain:
  application:
    name: gulimall-third-party
server:
  port: 30000

sms:
  host:
  path:
  appcode:
  sms-sign-id:
  template-id:

#alibaba:
#  cloud:
#    access-key:
#    secret-key:
#    oss:
#      bucket: slienceme
#      endpoint: oss-cn-beijing.aliyuncs.com
